DROP TABLE IF EXISTS Kuluttaja CASCADE;
DROP TABLE IF EXISTS Jaakaappi CASCADE;
DROP TABLE IF EXISTS Syojat CASCADE;
DROP TABLE IF EXISTS Elintarvike CASCADE;
DROP TABLE IF EXISTS Elintarviketyyppi CASCADE;
DROP TABLE IF EXISTS Luokittelu CASCADE;
